wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: huggingface
    huggingface_version: 3.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    start_time: 1631859408
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      2:
      - 1
      - 3
      - 5
      - 11
      4: 3.7.3
      5: 0.12.2
      6: 3.5.1
      8:
      - 5
